=== andriiyanko/EPAM_Projects/Xml_project/target/classes/xml/beerXSD.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="beers"
           xmlns="beers"
           elementFormDefault="qualified">

    <xs:element name = 'beers'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name = 'beer' type = 'beerType' minOccurs = '0'
                            maxOccurs = 'unbounded' />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name = "beerType">
        <xs:sequence>
            <xs:element name = "name" type = "xs:string"/>
            <xs:element name = "type" type = "xs:string"/>
            <xs:element name = "al" type = "xs:boolean"/>
            <xs:element name = "manufacturer" type = "xs:string"/>
            <xs:element name="ingredients">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="ingredient" type="xs:string"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="chars">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="alcFraction">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="0.0"/>
                                    <xs:maxInclusive value="15.0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="transparency">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:fractionDigits value="100"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="filtered" type="xs:boolean"/>
                        <xs:element name="nutritions">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="spillMethod">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="vol">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:decimal">
                                                <xs:minExclusive value="0"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="tankMaterial" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name = 'beerNo' type = 'xs:integer'/>
    </xs:complexType>
</xs:schema>

=== andriiyanko/EPAM_Projects/Xml_project/target/classes/xml/beerXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="beerXSLT.xsl"?>

<beers xmlns="beers"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="beerXSD.xsd">
    <beer beerNo="0">
        <name>golden ale</name>
        <type>ale</type>
        <al>true</al>
        <manufacturer>varvar brew</manufacturer>
        <ingredients>
            <ingredient>water</ingredient>
            <ingredient>hop</ingredient>
            <ingredient>malt</ingredient>
        </ingredients>
        <chars>
            <alcFraction>6.8</alcFraction>
            <transparency>21</transparency>
            <filtered>false</filtered>
            <nutritions>20</nutritions>
            <spillMethod>
                <vol>0.33</vol>
                <tankMaterial>glass</tankMaterial>
            </spillMethod>
        </chars>
    </beer>
    <beer beerNo="1">
        <name>milk stout</name>
        <type>stout</type>
        <al>true</al>
        <manufacturer>varvar brew</manufacturer>
        <ingredients>
            <ingredient>water</ingredient>
            <ingredient>hop</ingredient>
            <ingredient>malt</ingredient>
            <ingredient>lactose</ingredient>
        </ingredients>
        <chars>
            <alcFraction>4.7</alcFraction>
            <transparency>18</transparency>
            <filtered>false</filtered>
            <nutritions>50</nutritions>
            <spillMethod>
                <vol>0.33</vol>
                <tankMaterial>glass</tankMaterial>
            </spillMethod>
        </chars>
    </beer>
    <beer beerNo="2">
        <name>pumpeii</name>
        <type>pumpkin porter</type>
        <al>true</al>
        <manufacturer>varvar brew</manufacturer>
        <ingredients>
            <ingredient>water</ingredient>
            <ingredient>hop</ingredient>
            <ingredient>malt</ingredient>
            <ingredient>pumpkin</ingredient>
        </ingredients>
        <chars>
            <alcFraction>5.5</alcFraction>
            <transparency>12.8</transparency>
            <filtered>false</filtered>
            <nutritions>60</nutritions>
            <spillMethod>
                <vol>0.33</vol>
                <tankMaterial>glass</tankMaterial>
            </spillMethod>
        </chars>
    </beer>
    <beer beerNo="3">
        <name>stella artois</name>
        <type>lager</type>
        <al>false</al>
        <manufacturer>stella artois</manufacturer>
        <ingredients>
            <ingredient>water</ingredient>
            <ingredient>hop</ingredient>
            <ingredient>malt</ingredient>
        </ingredients>
        <chars>
            <alcFraction>0.0</alcFraction>
            <transparency>5.0</transparency>
            <filtered>true</filtered>
            <nutritions>25</nutritions>
            <spillMethod>
                <vol>0.5</vol>
                <tankMaterial>plastic</tankMaterial>
            </spillMethod>
        </chars>
    </beer>
</beers>
